### ISSUE TITLE
Is anyone monitoring this project?

### ISSUE THREAD

**Issue by bbimber** [francois-a/rnaseqc#3]
Hello,

My lab has been using the original RNAseqc for a while and likes the tool.  I had been looking for the source code for a long time and just came across this.  It looks like it would be pretty easy to migrate the code to a more modern build, java version and picard/gatk versions.  I can fork the repo and do this.  I'm just writing to see if anyone is actively watching this repo and if there was interest in some discussion around this?

**Comment by francois-a** [comment]
Hi,
Thanks for using RNA-SeQC and your interest in contributing. We have already published a new version of this software, with many enhancements and new metrics, at https://github.com/broadinstitute/rnaseqc. Feedback and contributions are welcome!
